package clinica_juridica.backend.dto.stats;

public enum TipoReporte {
    // A. Detalle por Materias
    MATERIA_CIVIL_SUCESIONES,
    MATERIA_CIVIL_FAMILIA_ORDINARIOS,
    MATERIA_CIVIL_FAMILIA_PROTECCION,
    MATERIA_CIVIL_PERSONAS,
    MATERIA_CIVIL_BIENES,
    MATERIA_CIVIL_CONTRATOS,
    MATERIA_PENAL,
    MATERIA_LABORAL,
    MATERIA_MERCANTIL,
    MATERIA_OTROS,

    // B. Estadísticas Demográficas y Geográficas
    RESUMEN_CASOS_POR_MATERIA,
    CLASIFICACION_POR_GENERO,
    USUARIOS_POR_ESTADO,
    USUARIOS_POR_PARROQUIA,

    // C. Unidades Especiales
    CONCILIACION_RESUMEN,
    DEFENSORIA_NNA_BENEFICIARIOS,
    DEFENSORIA_NNA_TIPOS_CASOS,
    DEFENSORIA_NNA_UBICACION,

    // D. Gestión y Formación
    VOLUNTARIADO_BENEFICIARIOS,
    FORMACION_ACADEMICA,
    HISTORICO_CASOS,
    TOTAL_BENEFICIARIOS
}
